/**
 * Regenerates `prisma/seed/vehicles.ts` from
 * `prisma/seed/data/vehicle-catalogue.csv` (the founder-supplied Bulgarian
 * used-parts vehicle catalogue, #4 / #21).
 *
 *   npm run build:vehicle-fixture
 *
 * Re-run whenever the CSV changes. The generated file is committed so the seed
 * and tests don't need the CSV at runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { slugify } from "../lib/services/slug";

const CSV = resolve("prisma/seed/data/vehicle-catalogue.csv");
const OUT = resolve("prisma/seed/vehicles.ts");

/** Minimal RFC-4180 parser (quoted fields, embedded commas + newlines). */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.length > 1 || row[0] !== "") rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function chassisCodes(raw: string): string[] {
  const seen = new Set<string>();
  for (const tok of raw.split(/[\s/()]+/)) {
    const t = tok.trim();
    if (t && t.length <= 6 && /\d/.test(t) && /^[A-Za-z0-9.]+$/.test(t)) {
      seen.add(t.toUpperCase());
    }
  }
  return [...seen];
}

const rows = parseCsv(readFileSync(CSV, "utf8"));
const header = rows[0];
const col = (name: string) => header.indexOf(name);
const iKey = col("catalogue_key");
const iMake = col("make");
const iGroup = col("model_group");
const iGen = col("generation_name");
const iChassis = col("chassis_platform_code");
const iStart = col("production_start_year");
const iEnd = col("production_end_year");

interface MakeSeed { slug: string; name: string }
interface ModelGroupSeed { slug: string; makeSlug: string; name: string }
interface GenerationSeed {
  slug: string; modelGroupSlug: string; label: string;
  chassisCodes: string[]; productionStart: number; productionEnd: number | null;
}

const makes = new Map<string, MakeSeed>();
const modelGroups = new Map<string, ModelGroupSeed>();
const generations: GenerationSeed[] = [];

for (const r of rows.slice(1)) {
  if (!r[iKey]) continue;
  const make = r[iMake].trim();
  const group = r[iGroup].trim();
  const makeSlug = slugify(make);
  const modelGroupSlug = `${makeSlug}-${slugify(group)}`;
  const start = Number(r[iStart]);
  const endRaw = r[iEnd].trim();
  const end = endRaw ? Number(endRaw) : null;

  if (!makes.has(makeSlug)) makes.set(makeSlug, { slug: makeSlug, name: make });
  if (!modelGroups.has(modelGroupSlug)) {
    modelGroups.set(modelGroupSlug, { slug: modelGroupSlug, makeSlug, name: group });
  }
  generations.push({
    slug: slugify(r[iKey]),
    modelGroupSlug,
    label: `${r[iGen].trim()} (${start}–${end ?? "now"})`,
    chassisCodes: chassisCodes(r[iChassis]),
    productionStart: start,
    productionEnd: end,
  });
}

const banner = `/**
 * GENERATED by scripts/build-vehicle-fixture.ts from
 * prisma/seed/data/vehicle-catalogue.csv — do not hand-edit.
 *
 * Bulgarian used-parts vehicle catalogue (#4 / #21), generation-grain.
 * ${makes.size} makes / ${modelGroups.size} model groups / ${generations.length} generations.
 * Some rows are flagged for local confirmation — see the confirmation-queue CSV
 * and docs/spec/seed-data.md. They are imported as active for v1.
 */
`;

const body = `export interface MakeSeed {
  slug: string;
  name: string;
  country?: string;
}

export interface ModelGroupSeed {
  slug: string;
  makeSlug: string;
  name: string;
}

export interface GenerationSeed {
  slug: string;
  modelGroupSlug: string;
  label: string;
  chassisCodes: string[];
  productionStart: number;
  productionEnd: number | null;
}

export const MAKES: MakeSeed[] = ${JSON.stringify([...makes.values()], null, 2)};

export const MODEL_GROUPS: ModelGroupSeed[] = ${JSON.stringify([...modelGroups.values()], null, 2)};

export const GENERATIONS: GenerationSeed[] = ${JSON.stringify(generations, null, 2)};
`;

writeFileSync(OUT, banner + "\n" + body);
console.log(
  `wrote ${OUT}: ${makes.size} makes, ${modelGroups.size} model groups, ${generations.length} generations`,
);
