#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

NEON_CONSOLE="https://console.neon.tech/app/projects"

# read_conn KEY "Prompt" — hidden read for a connection string, with validation
# and retry. Hidden input gives no echo, so a human who re-pastes (thinking the
# first paste didn't register) silently concatenates copies. This rejects that,
# plus wrapping quotes / a "KEY=" prefix / a stray CR from a Windows paste.
read_conn() {
  local key="$1" prompt="$2" input schemes
  while true; do
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    read -rs input || true
    printf '\n'
    input="${input//$'\r'/}"
    input="${input#DATABASE_URL=}"; input="${input#DIRECT_URL=}"; input="${input#TEST_DATABASE_URL=}"
    input="${input%\"}"; input="${input#\"}"
    input="${input%\'}"; input="${input#\'}"
    if [[ -z "$input" ]]; then warn "empty — paste the connection string, then Enter"; continue; fi
    if [[ "$input" == *[[:space:]]* ]]; then warn "contains a space — extra text got pasted; try again"; continue; fi
    if [[ "$input" != postgres*://* ]]; then warn "must start with postgres:// or postgresql://; try again"; continue; fi
    schemes=$(grep -o '://' <<<"$input" | grep -c '')
    if [[ "$schemes" != "1" ]]; then
      warn "found $schemes '://' — the value was pasted more than once. Paste it ONCE, then Enter."
      continue
    fi
    break
  done
  # Neon compute scales to zero; give the first connection time to wake it.
  if [[ "$input" != *connect_timeout=* ]]; then
    [[ "$input" == *\?* ]] && input="${input}&connect_timeout=15" || input="${input}?connect_timeout=15"
  fi
  printf -v "$key" '%s' "$input"
}

banner "Connect Neon (development + test) to this repo"

# ── Stage 1 · Preflight ──────────────────────────────────────────────────
stage "Preflight: safety checks"
say "This wizard writes local env files and runs Prisma migrations against your"
say "Neon development and test branches. It never touches the production branch."
printf '\n'

cd "$(git rev-parse --show-toplevel)"

for f in .env.local .env.test.local; do
  if git check-ignore -q "$f"; then
    printf '  %s✓%s %s is gitignored\n' "$GREEN" "$RESET" "$f"
  else
    printf '  %s✖ %s is NOT gitignored — aborting so a secret is never committed.%s\n' "$RED" "$f" "$RESET"
    exit 1
  fi
done

[[ -d node_modules ]] || { warn "run 'npm install' first"; exit 1; }
printf '  %s✓%s dependencies installed\n\n' "$GREEN" "$RESET"

note "Values are written straight into .env.local / .env.test.local as you paste."
note "Templates with docs: .env.example, .env.test.example"
printf '\n'
confirm "You will paste ONLY the development and test branch strings — never production?" \
  || { warn "stopping — re-run when ready"; exit 1; }

# ── Stage 2 · Development branch → .env.local ─────────────────────────────
ENV_FILE=".env.local"
stage "Neon 'development' branch → .env.local"
open_url "$NEON_CONSOLE"
step "Open your project, then the Branches tab, then the 'development' branch."
step "Click 'Connect to your database' (top right)."
step "Database: neondb.  Role: pick your app role.  Turn 'Connection pooling' ON."
step "Copy the connection string (starts postgresql://, host ends -pooler...neon.tech)."
read_conn DATABASE_URL "Paste the POOLED development connection string:"
write_env DATABASE_URL "$DATABASE_URL"
printf '\n'
step "Back in the Connect dialog, turn 'Connection pooling' OFF (direct connection)."
step "Copy that string (host has NO -pooler)."
read_conn DIRECT_URL "Paste the DIRECT development connection string:"
write_env DIRECT_URL "$DIRECT_URL"

# ── Stage 3 · Auth secret → .env.local ───────────────────────────────────
stage "Better Auth secret → .env.local"
say "Generating a random 32-byte secret for local sign-in."
if command -v openssl >/dev/null 2>&1; then
  SECRET=$(openssl rand -base64 32)
else
  SECRET=$(head -c 32 /dev/urandom | base64)
fi
write_env BETTER_AUTH_SECRET "$SECRET"
write_env BETTER_AUTH_URL "http://localhost:3000"
unset SECRET

# ── Stage 4 · Test branch → .env.test.local ──────────────────────────────
ENV_FILE=".env.test.local"
stage "Neon 'test' branch → .env.test.local"
say "Integration tests own this branch — migrations and test rows land here only."
open_url "$NEON_CONSOLE"
step "Open the Branches tab, then the 'test' branch."
step "Click 'Connect to your database'."
step "Turn 'Connection pooling' OFF — use the DIRECT connection string."
step "Copy it (host has NO -pooler)."
read_conn TEST_DATABASE_URL "Paste the DIRECT test connection string:"
if [[ "$TEST_DATABASE_URL" == "$DIRECT_URL" || "$TEST_DATABASE_URL" == "$DATABASE_URL" ]]; then
  printf '  %s✖ that is the development string — the test branch must be a different database.%s\n' "$RED" "$RESET"
  exit 1
fi
write_env TEST_DATABASE_URL "$TEST_DATABASE_URL"
unset DATABASE_URL DIRECT_URL TEST_DATABASE_URL

# ── Stage 5 · First migration (development, then test) ────────────────────
stage "Create & apply the first migration"
say "Creates prisma/migrations/…_init from schema.prisma, applies it to the"
say "development branch, then applies it to the test branch."
printf '\n'
confirm "Run migrations now?" || { warn "skipped — run 'npm run db:migrate -- --name init' later"; exit 1; }
npm run db:migrate -- --name init --skip-seed
printf '\n'
say "Applying the same migration to the test branch..."
npm run db:migrate:test

# ── Stage 6 · Seed the development branch ─────────────────────────────────
stage "Seed the development branch"
say "Loads the demo dataset (docs/spec/seed-data.md). The seed wipes first, so"
say "it is safe to re-run. The test branch is left empty for tests to populate."
printf '\n'
if confirm "Seed development now?"; then
  npm run db:seed
else
  SKIPPED+=("npm run db:seed")
fi

# ── Stage 7 · Verify ─────────────────────────────────────────────────────
stage "Verify"
say "Running the integration smoke test against the test branch..."
printf '\n'
npm run test:integration
printf '\n'
say "Now start the app and check the DB from the browser:"
step "npm run dev"
step "open http://localhost:3000/api/health  →  expect {\"status\":\"ok\",\"db\":\"ok\"}"
pause "Press Enter when done"

finish
