/**
 * GENERATED by scripts/build-vehicle-fixture.ts from
 * prisma/seed/data/vehicle-catalogue.csv — do not hand-edit.
 *
 * Bulgarian used-parts vehicle catalogue (#4 / #21), generation-grain.
 * 14 makes / 50 model groups / 138 generations.
 * Some rows are flagged for local confirmation — see the confirmation-queue CSV
 * and docs/spec/seed-data.md. They are imported as active for v1.
 */

export interface MakeSeed {
  slug: string;
  name: string;
  country?: string;
}

export interface ModelGroupSeed {
  slug: string;
  makeSlug: string;
  name: string;
}

export interface GenerationSeed {
  slug: string;
  modelGroupSlug: string;
  label: string;
  chassisCodes: string[];
  productionStart: number;
  productionEnd: number | null;
}

export const MAKES: MakeSeed[] = [
  {
    "slug": "volkswagen",
    "name": "Volkswagen"
  },
  {
    "slug": "mercedes-benz",
    "name": "Mercedes-Benz"
  },
  {
    "slug": "bmw",
    "name": "BMW"
  },
  {
    "slug": "audi",
    "name": "Audi"
  },
  {
    "slug": "opel",
    "name": "Opel"
  },
  {
    "slug": "ford",
    "name": "Ford"
  },
  {
    "slug": "renault",
    "name": "Renault"
  },
  {
    "slug": "peugeot",
    "name": "Peugeot"
  },
  {
    "slug": "citroen",
    "name": "Citroen"
  },
  {
    "slug": "skoda",
    "name": "Skoda"
  },
  {
    "slug": "toyota",
    "name": "Toyota"
  },
  {
    "slug": "honda",
    "name": "Honda"
  },
  {
    "slug": "fiat",
    "name": "Fiat"
  },
  {
    "slug": "nissan",
    "name": "Nissan"
  }
];

export const MODEL_GROUPS: ModelGroupSeed[] = [
  {
    "slug": "volkswagen-golf",
    "makeSlug": "volkswagen",
    "name": "Golf"
  },
  {
    "slug": "volkswagen-passat",
    "makeSlug": "volkswagen",
    "name": "Passat"
  },
  {
    "slug": "volkswagen-polo",
    "makeSlug": "volkswagen",
    "name": "Polo"
  },
  {
    "slug": "volkswagen-touran",
    "makeSlug": "volkswagen",
    "name": "Touran"
  },
  {
    "slug": "volkswagen-tiguan",
    "makeSlug": "volkswagen",
    "name": "Tiguan"
  },
  {
    "slug": "mercedes-benz-c-class",
    "makeSlug": "mercedes-benz",
    "name": "C-Class"
  },
  {
    "slug": "mercedes-benz-e-class",
    "makeSlug": "mercedes-benz",
    "name": "E-Class"
  },
  {
    "slug": "mercedes-benz-a-class",
    "makeSlug": "mercedes-benz",
    "name": "A-Class"
  },
  {
    "slug": "mercedes-benz-m-class-gle",
    "makeSlug": "mercedes-benz",
    "name": "M-Class / GLE"
  },
  {
    "slug": "bmw-3-series",
    "makeSlug": "bmw",
    "name": "3 Series"
  },
  {
    "slug": "bmw-5-series",
    "makeSlug": "bmw",
    "name": "5 Series"
  },
  {
    "slug": "bmw-x3",
    "makeSlug": "bmw",
    "name": "X3"
  },
  {
    "slug": "bmw-x5",
    "makeSlug": "bmw",
    "name": "X5"
  },
  {
    "slug": "audi-a3",
    "makeSlug": "audi",
    "name": "A3"
  },
  {
    "slug": "audi-a4",
    "makeSlug": "audi",
    "name": "A4"
  },
  {
    "slug": "audi-a6",
    "makeSlug": "audi",
    "name": "A6"
  },
  {
    "slug": "audi-q5",
    "makeSlug": "audi",
    "name": "Q5"
  },
  {
    "slug": "opel-astra",
    "makeSlug": "opel",
    "name": "Astra"
  },
  {
    "slug": "opel-corsa",
    "makeSlug": "opel",
    "name": "Corsa"
  },
  {
    "slug": "opel-insignia",
    "makeSlug": "opel",
    "name": "Insignia"
  },
  {
    "slug": "opel-zafira",
    "makeSlug": "opel",
    "name": "Zafira"
  },
  {
    "slug": "ford-focus",
    "makeSlug": "ford",
    "name": "Focus"
  },
  {
    "slug": "ford-fiesta",
    "makeSlug": "ford",
    "name": "Fiesta"
  },
  {
    "slug": "ford-mondeo",
    "makeSlug": "ford",
    "name": "Mondeo"
  },
  {
    "slug": "ford-kuga",
    "makeSlug": "ford",
    "name": "Kuga"
  },
  {
    "slug": "renault-clio",
    "makeSlug": "renault",
    "name": "Clio"
  },
  {
    "slug": "renault-megane",
    "makeSlug": "renault",
    "name": "Megane"
  },
  {
    "slug": "renault-scenic",
    "makeSlug": "renault",
    "name": "Scenic"
  },
  {
    "slug": "renault-laguna",
    "makeSlug": "renault",
    "name": "Laguna"
  },
  {
    "slug": "peugeot-206",
    "makeSlug": "peugeot",
    "name": "206"
  },
  {
    "slug": "peugeot-207",
    "makeSlug": "peugeot",
    "name": "207"
  },
  {
    "slug": "peugeot-307",
    "makeSlug": "peugeot",
    "name": "307"
  },
  {
    "slug": "peugeot-308",
    "makeSlug": "peugeot",
    "name": "308"
  },
  {
    "slug": "citroen-c3",
    "makeSlug": "citroen",
    "name": "C3"
  },
  {
    "slug": "citroen-c4",
    "makeSlug": "citroen",
    "name": "C4"
  },
  {
    "slug": "citroen-c5",
    "makeSlug": "citroen",
    "name": "C5"
  },
  {
    "slug": "skoda-octavia",
    "makeSlug": "skoda",
    "name": "Octavia"
  },
  {
    "slug": "skoda-fabia",
    "makeSlug": "skoda",
    "name": "Fabia"
  },
  {
    "slug": "skoda-superb",
    "makeSlug": "skoda",
    "name": "Superb"
  },
  {
    "slug": "toyota-corolla",
    "makeSlug": "toyota",
    "name": "Corolla"
  },
  {
    "slug": "toyota-avensis",
    "makeSlug": "toyota",
    "name": "Avensis"
  },
  {
    "slug": "toyota-rav4",
    "makeSlug": "toyota",
    "name": "RAV4"
  },
  {
    "slug": "honda-civic",
    "makeSlug": "honda",
    "name": "Civic"
  },
  {
    "slug": "honda-cr-v",
    "makeSlug": "honda",
    "name": "CR-V"
  },
  {
    "slug": "fiat-punto",
    "makeSlug": "fiat",
    "name": "Punto"
  },
  {
    "slug": "fiat-panda",
    "makeSlug": "fiat",
    "name": "Panda"
  },
  {
    "slug": "fiat-doblo",
    "makeSlug": "fiat",
    "name": "Doblo"
  },
  {
    "slug": "nissan-qashqai",
    "makeSlug": "nissan",
    "name": "Qashqai"
  },
  {
    "slug": "nissan-x-trail",
    "makeSlug": "nissan",
    "name": "X-Trail"
  },
  {
    "slug": "nissan-micra",
    "makeSlug": "nissan",
    "name": "Micra"
  }
];

export const GENERATIONS: GenerationSeed[] = [
  {
    "slug": "volkswagen-golf-golf-iv-1j-1j1-1j5",
    "modelGroupSlug": "volkswagen-golf",
    "label": "Golf IV (1997–2006)",
    "chassisCodes": [
      "1J",
      "1J1",
      "1J5"
    ],
    "productionStart": 1997,
    "productionEnd": 2006
  },
  {
    "slug": "volkswagen-golf-golf-v-1k-1k1-1k5",
    "modelGroupSlug": "volkswagen-golf",
    "label": "Golf V (2003–2009)",
    "chassisCodes": [
      "1K",
      "1K1",
      "1K5"
    ],
    "productionStart": 2003,
    "productionEnd": 2009
  },
  {
    "slug": "volkswagen-golf-golf-vi-5k-aj-5k1-aj5",
    "modelGroupSlug": "volkswagen-golf",
    "label": "Golf VI (2008–2013)",
    "chassisCodes": [
      "5K",
      "5K1",
      "AJ5"
    ],
    "productionStart": 2008,
    "productionEnd": 2013
  },
  {
    "slug": "volkswagen-golf-golf-vii-5g-ba-5g1-ba5",
    "modelGroupSlug": "volkswagen-golf",
    "label": "Golf VII (2012–2020)",
    "chassisCodes": [
      "5G",
      "5G1",
      "BA5"
    ],
    "productionStart": 2012,
    "productionEnd": 2020
  },
  {
    "slug": "volkswagen-passat-b5-pre-facelift-3b-3b2-3b5",
    "modelGroupSlug": "volkswagen-passat",
    "label": "B5 (pre-facelift) (1996–2000)",
    "chassisCodes": [
      "3B",
      "3B2",
      "3B5"
    ],
    "productionStart": 1996,
    "productionEnd": 2000
  },
  {
    "slug": "volkswagen-passat-b5-5-facelift-operational-split-3bg-3b3-3b6",
    "modelGroupSlug": "volkswagen-passat",
    "label": "B5.5 (facelift; operational split) (2000–2005)",
    "chassisCodes": [
      "3BG",
      "3B3",
      "3B6"
    ],
    "productionStart": 2000,
    "productionEnd": 2005
  },
  {
    "slug": "volkswagen-passat-b6-3c-3c2-3c5",
    "modelGroupSlug": "volkswagen-passat",
    "label": "B6 (2005–2010)",
    "chassisCodes": [
      "3C",
      "3C2",
      "3C5"
    ],
    "productionStart": 2005,
    "productionEnd": 2010
  },
  {
    "slug": "volkswagen-passat-b7-3c-362-365",
    "modelGroupSlug": "volkswagen-passat",
    "label": "B7 (2010–2014)",
    "chassisCodes": [
      "3C",
      "362",
      "365"
    ],
    "productionStart": 2010,
    "productionEnd": 2014
  },
  {
    "slug": "volkswagen-passat-b8-3g-3g2-3g5",
    "modelGroupSlug": "volkswagen-passat",
    "label": "B8 (2014–2023)",
    "chassisCodes": [
      "3G",
      "3G2",
      "3G5"
    ],
    "productionStart": 2014,
    "productionEnd": 2023
  },
  {
    "slug": "volkswagen-polo-polo-iii-6n-6n1-6n2",
    "modelGroupSlug": "volkswagen-polo",
    "label": "Polo III (1994–2001)",
    "chassisCodes": [
      "6N",
      "6N1",
      "6N2"
    ],
    "productionStart": 1994,
    "productionEnd": 2001
  },
  {
    "slug": "volkswagen-polo-polo-iv-9n-9n1-9n3",
    "modelGroupSlug": "volkswagen-polo",
    "label": "Polo IV (2001–2009)",
    "chassisCodes": [
      "9N",
      "9N1",
      "9N3"
    ],
    "productionStart": 2001,
    "productionEnd": 2009
  },
  {
    "slug": "volkswagen-polo-polo-v-6r-6c",
    "modelGroupSlug": "volkswagen-polo",
    "label": "Polo V (2009–2017)",
    "chassisCodes": [
      "6R",
      "6C"
    ],
    "productionStart": 2009,
    "productionEnd": 2017
  },
  {
    "slug": "volkswagen-touran-touran-i-1t-1t1-1t2-1t3",
    "modelGroupSlug": "volkswagen-touran",
    "label": "Touran I (2003–2015)",
    "chassisCodes": [
      "1T",
      "1T1",
      "1T2",
      "1T3"
    ],
    "productionStart": 2003,
    "productionEnd": 2015
  },
  {
    "slug": "volkswagen-tiguan-tiguan-i-5n",
    "modelGroupSlug": "volkswagen-tiguan",
    "label": "Tiguan I (2007–2016)",
    "chassisCodes": [
      "5N"
    ],
    "productionStart": 2007,
    "productionEnd": 2016
  },
  {
    "slug": "volkswagen-tiguan-tiguan-ii-ad1-bw2-allspace-separate-fitment",
    "modelGroupSlug": "volkswagen-tiguan",
    "label": "Tiguan II (2016–2024)",
    "chassisCodes": [
      "AD1",
      "BW2"
    ],
    "productionStart": 2016,
    "productionEnd": 2024
  },
  {
    "slug": "mercedes-benz-c-class-w202-s202-w202-s202",
    "modelGroupSlug": "mercedes-benz-c-class",
    "label": "W202/S202 (1993–2001)",
    "chassisCodes": [
      "W202",
      "S202"
    ],
    "productionStart": 1993,
    "productionEnd": 2001
  },
  {
    "slug": "mercedes-benz-c-class-w203-s203-w203-s203",
    "modelGroupSlug": "mercedes-benz-c-class",
    "label": "W203/S203 (2000–2007)",
    "chassisCodes": [
      "W203",
      "S203"
    ],
    "productionStart": 2000,
    "productionEnd": 2007
  },
  {
    "slug": "mercedes-benz-c-class-w204-s204-w204-s204",
    "modelGroupSlug": "mercedes-benz-c-class",
    "label": "W204/S204 (2007–2014)",
    "chassisCodes": [
      "W204",
      "S204"
    ],
    "productionStart": 2007,
    "productionEnd": 2014
  },
  {
    "slug": "mercedes-benz-c-class-w205-s205-w205-s205",
    "modelGroupSlug": "mercedes-benz-c-class",
    "label": "W205/S205 (2014–2021)",
    "chassisCodes": [
      "W205",
      "S205"
    ],
    "productionStart": 2014,
    "productionEnd": 2021
  },
  {
    "slug": "mercedes-benz-e-class-w210-s210-w210-s210",
    "modelGroupSlug": "mercedes-benz-e-class",
    "label": "W210/S210 (1995–2003)",
    "chassisCodes": [
      "W210",
      "S210"
    ],
    "productionStart": 1995,
    "productionEnd": 2003
  },
  {
    "slug": "mercedes-benz-e-class-w211-s211-w211-s211",
    "modelGroupSlug": "mercedes-benz-e-class",
    "label": "W211/S211 (2002–2009)",
    "chassisCodes": [
      "W211",
      "S211"
    ],
    "productionStart": 2002,
    "productionEnd": 2009
  },
  {
    "slug": "mercedes-benz-e-class-w212-s212-w212-s212",
    "modelGroupSlug": "mercedes-benz-e-class",
    "label": "W212/S212 (2009–2016)",
    "chassisCodes": [
      "W212",
      "S212"
    ],
    "productionStart": 2009,
    "productionEnd": 2016
  },
  {
    "slug": "mercedes-benz-e-class-w213-s213-w213-s213",
    "modelGroupSlug": "mercedes-benz-e-class",
    "label": "W213/S213 (2016–2023)",
    "chassisCodes": [
      "W213",
      "S213"
    ],
    "productionStart": 2016,
    "productionEnd": 2023
  },
  {
    "slug": "mercedes-benz-a-class-w168-w168",
    "modelGroupSlug": "mercedes-benz-a-class",
    "label": "W168 (1997–2004)",
    "chassisCodes": [
      "W168"
    ],
    "productionStart": 1997,
    "productionEnd": 2004
  },
  {
    "slug": "mercedes-benz-a-class-w169-w169",
    "modelGroupSlug": "mercedes-benz-a-class",
    "label": "W169 (2004–2012)",
    "chassisCodes": [
      "W169"
    ],
    "productionStart": 2004,
    "productionEnd": 2012
  },
  {
    "slug": "mercedes-benz-a-class-w176-w176",
    "modelGroupSlug": "mercedes-benz-a-class",
    "label": "W176 (2012–2018)",
    "chassisCodes": [
      "W176"
    ],
    "productionStart": 2012,
    "productionEnd": 2018
  },
  {
    "slug": "mercedes-benz-m-class-gle-w163-m-class-w163",
    "modelGroupSlug": "mercedes-benz-m-class-gle",
    "label": "W163 M-Class (1997–2005)",
    "chassisCodes": [
      "W163"
    ],
    "productionStart": 1997,
    "productionEnd": 2005
  },
  {
    "slug": "mercedes-benz-m-class-gle-w164-m-class-w164",
    "modelGroupSlug": "mercedes-benz-m-class-gle",
    "label": "W164 M-Class (2005–2011)",
    "chassisCodes": [
      "W164"
    ],
    "productionStart": 2005,
    "productionEnd": 2011
  },
  {
    "slug": "mercedes-benz-m-class-gle-w166-m-class-gle-w166",
    "modelGroupSlug": "mercedes-benz-m-class-gle",
    "label": "W166 M-Class / GLE (2011–2019)",
    "chassisCodes": [
      "W166"
    ],
    "productionStart": 2011,
    "productionEnd": 2019
  },
  {
    "slug": "bmw-3-series-e46-e46",
    "modelGroupSlug": "bmw-3-series",
    "label": "E46 (1997–2006)",
    "chassisCodes": [
      "E46"
    ],
    "productionStart": 1997,
    "productionEnd": 2006
  },
  {
    "slug": "bmw-3-series-e9x-e90-e91-e92-e93",
    "modelGroupSlug": "bmw-3-series",
    "label": "E9x (2004–2013)",
    "chassisCodes": [
      "E90",
      "E91",
      "E92",
      "E93"
    ],
    "productionStart": 2004,
    "productionEnd": 2013
  },
  {
    "slug": "bmw-3-series-f3x-f30-f31-f34",
    "modelGroupSlug": "bmw-3-series",
    "label": "F3x (2011–2020)",
    "chassisCodes": [
      "F30",
      "F31",
      "F34"
    ],
    "productionStart": 2011,
    "productionEnd": 2020
  },
  {
    "slug": "bmw-5-series-e39-e39",
    "modelGroupSlug": "bmw-5-series",
    "label": "E39 (1995–2004)",
    "chassisCodes": [
      "E39"
    ],
    "productionStart": 1995,
    "productionEnd": 2004
  },
  {
    "slug": "bmw-5-series-e6x-e60-e61",
    "modelGroupSlug": "bmw-5-series",
    "label": "E6x (2003–2010)",
    "chassisCodes": [
      "E60",
      "E61"
    ],
    "productionStart": 2003,
    "productionEnd": 2010
  },
  {
    "slug": "bmw-5-series-f1x-f10-f11-f07",
    "modelGroupSlug": "bmw-5-series",
    "label": "F1x (2009–2017)",
    "chassisCodes": [
      "F10",
      "F11",
      "F07"
    ],
    "productionStart": 2009,
    "productionEnd": 2017
  },
  {
    "slug": "bmw-5-series-g3x-g30-g31",
    "modelGroupSlug": "bmw-5-series",
    "label": "G3x (2016–2024)",
    "chassisCodes": [
      "G30",
      "G31"
    ],
    "productionStart": 2016,
    "productionEnd": 2024
  },
  {
    "slug": "bmw-x3-e83-e83",
    "modelGroupSlug": "bmw-x3",
    "label": "E83 (2003–2010)",
    "chassisCodes": [
      "E83"
    ],
    "productionStart": 2003,
    "productionEnd": 2010
  },
  {
    "slug": "bmw-x3-f25-f25",
    "modelGroupSlug": "bmw-x3",
    "label": "F25 (2010–2017)",
    "chassisCodes": [
      "F25"
    ],
    "productionStart": 2010,
    "productionEnd": 2017
  },
  {
    "slug": "bmw-x3-g01-g01",
    "modelGroupSlug": "bmw-x3",
    "label": "G01 (2017–2024)",
    "chassisCodes": [
      "G01"
    ],
    "productionStart": 2017,
    "productionEnd": 2024
  },
  {
    "slug": "bmw-x5-e53-e53",
    "modelGroupSlug": "bmw-x5",
    "label": "E53 (1999–2006)",
    "chassisCodes": [
      "E53"
    ],
    "productionStart": 1999,
    "productionEnd": 2006
  },
  {
    "slug": "bmw-x5-e70-e70",
    "modelGroupSlug": "bmw-x5",
    "label": "E70 (2006–2013)",
    "chassisCodes": [
      "E70"
    ],
    "productionStart": 2006,
    "productionEnd": 2013
  },
  {
    "slug": "bmw-x5-f15-f15-f85-x5-m-separate-fitment",
    "modelGroupSlug": "bmw-x5",
    "label": "F15 (2013–2018)",
    "chassisCodes": [
      "F15",
      "F85",
      "X5"
    ],
    "productionStart": 2013,
    "productionEnd": 2018
  },
  {
    "slug": "audi-a3-8l-8l",
    "modelGroupSlug": "audi-a3",
    "label": "8L (1996–2003)",
    "chassisCodes": [
      "8L"
    ],
    "productionStart": 1996,
    "productionEnd": 2003
  },
  {
    "slug": "audi-a3-8p-8p",
    "modelGroupSlug": "audi-a3",
    "label": "8P (2003–2013)",
    "chassisCodes": [
      "8P"
    ],
    "productionStart": 2003,
    "productionEnd": 2013
  },
  {
    "slug": "audi-a3-8v-8v",
    "modelGroupSlug": "audi-a3",
    "label": "8V (2012–2020)",
    "chassisCodes": [
      "8V"
    ],
    "productionStart": 2012,
    "productionEnd": 2020
  },
  {
    "slug": "audi-a4-b5-8d",
    "modelGroupSlug": "audi-a4",
    "label": "B5 (1994–2001)",
    "chassisCodes": [
      "8D"
    ],
    "productionStart": 1994,
    "productionEnd": 2001
  },
  {
    "slug": "audi-a4-b6-8e-8h",
    "modelGroupSlug": "audi-a4",
    "label": "B6 (2000–2006)",
    "chassisCodes": [
      "8E",
      "8H"
    ],
    "productionStart": 2000,
    "productionEnd": 2006
  },
  {
    "slug": "audi-a4-b7-8e-8h",
    "modelGroupSlug": "audi-a4",
    "label": "B7 (2004–2009)",
    "chassisCodes": [
      "8E",
      "8H"
    ],
    "productionStart": 2004,
    "productionEnd": 2009
  },
  {
    "slug": "audi-a4-b8-8k",
    "modelGroupSlug": "audi-a4",
    "label": "B8 (2007–2016)",
    "chassisCodes": [
      "8K"
    ],
    "productionStart": 2007,
    "productionEnd": 2016
  },
  {
    "slug": "audi-a4-b9-8w",
    "modelGroupSlug": "audi-a4",
    "label": "B9 (2015–2024)",
    "chassisCodes": [
      "8W"
    ],
    "productionStart": 2015,
    "productionEnd": 2024
  },
  {
    "slug": "audi-a6-c5-4b",
    "modelGroupSlug": "audi-a6",
    "label": "C5 (1997–2005)",
    "chassisCodes": [
      "4B"
    ],
    "productionStart": 1997,
    "productionEnd": 2005
  },
  {
    "slug": "audi-a6-c6-4f",
    "modelGroupSlug": "audi-a6",
    "label": "C6 (2004–2011)",
    "chassisCodes": [
      "4F"
    ],
    "productionStart": 2004,
    "productionEnd": 2011
  },
  {
    "slug": "audi-a6-c7-4g",
    "modelGroupSlug": "audi-a6",
    "label": "C7 (2010–2018)",
    "chassisCodes": [
      "4G"
    ],
    "productionStart": 2010,
    "productionEnd": 2018
  },
  {
    "slug": "audi-q5-q5-i-8r",
    "modelGroupSlug": "audi-q5",
    "label": "Q5 I (2008–2017)",
    "chassisCodes": [
      "8R"
    ],
    "productionStart": 2008,
    "productionEnd": 2017
  },
  {
    "slug": "audi-q5-q5-ii-fy",
    "modelGroupSlug": "audi-q5",
    "label": "Q5 II (2016–2024)",
    "chassisCodes": [],
    "productionStart": 2016,
    "productionEnd": 2024
  },
  {
    "slug": "opel-astra-astra-g-t98",
    "modelGroupSlug": "opel-astra",
    "label": "Astra G (1998–2009)",
    "chassisCodes": [
      "T98"
    ],
    "productionStart": 1998,
    "productionEnd": 2009
  },
  {
    "slug": "opel-astra-astra-h-a04",
    "modelGroupSlug": "opel-astra",
    "label": "Astra H (2004–2014)",
    "chassisCodes": [
      "A04"
    ],
    "productionStart": 2004,
    "productionEnd": 2014
  },
  {
    "slug": "opel-astra-astra-j-p10",
    "modelGroupSlug": "opel-astra",
    "label": "Astra J (2009–2018)",
    "chassisCodes": [
      "P10"
    ],
    "productionStart": 2009,
    "productionEnd": 2018
  },
  {
    "slug": "opel-astra-astra-k-b16",
    "modelGroupSlug": "opel-astra",
    "label": "Astra K (2015–2021)",
    "chassisCodes": [
      "B16"
    ],
    "productionStart": 2015,
    "productionEnd": 2021
  },
  {
    "slug": "opel-corsa-corsa-c-x01",
    "modelGroupSlug": "opel-corsa",
    "label": "Corsa C (2000–2006)",
    "chassisCodes": [
      "X01"
    ],
    "productionStart": 2000,
    "productionEnd": 2006
  },
  {
    "slug": "opel-corsa-corsa-d-s07",
    "modelGroupSlug": "opel-corsa",
    "label": "Corsa D (2006–2014)",
    "chassisCodes": [
      "S07"
    ],
    "productionStart": 2006,
    "productionEnd": 2014
  },
  {
    "slug": "opel-corsa-corsa-e-x15",
    "modelGroupSlug": "opel-corsa",
    "label": "Corsa E (2014–2019)",
    "chassisCodes": [
      "X15"
    ],
    "productionStart": 2014,
    "productionEnd": 2019
  },
  {
    "slug": "opel-insignia-insignia-a-g09",
    "modelGroupSlug": "opel-insignia",
    "label": "Insignia A (2008–2017)",
    "chassisCodes": [
      "G09"
    ],
    "productionStart": 2008,
    "productionEnd": 2017
  },
  {
    "slug": "opel-insignia-insignia-b-z18",
    "modelGroupSlug": "opel-insignia",
    "label": "Insignia B (2017–2022)",
    "chassisCodes": [
      "Z18"
    ],
    "productionStart": 2017,
    "productionEnd": 2022
  },
  {
    "slug": "opel-zafira-zafira-a-t98",
    "modelGroupSlug": "opel-zafira",
    "label": "Zafira A (1999–2005)",
    "chassisCodes": [
      "T98"
    ],
    "productionStart": 1999,
    "productionEnd": 2005
  },
  {
    "slug": "opel-zafira-zafira-b-a05",
    "modelGroupSlug": "opel-zafira",
    "label": "Zafira B (2005–2014)",
    "chassisCodes": [
      "A05"
    ],
    "productionStart": 2005,
    "productionEnd": 2014
  },
  {
    "slug": "opel-zafira-zafira-c-tourer-p12",
    "modelGroupSlug": "opel-zafira",
    "label": "Zafira C / Tourer (2011–2019)",
    "chassisCodes": [
      "P12"
    ],
    "productionStart": 2011,
    "productionEnd": 2019
  },
  {
    "slug": "ford-focus-mk1-europe-c170",
    "modelGroupSlug": "ford-focus",
    "label": "Mk1 (Europe) (1998–2005)",
    "chassisCodes": [
      "C170"
    ],
    "productionStart": 1998,
    "productionEnd": 2005
  },
  {
    "slug": "ford-focus-mk2-europe-c307",
    "modelGroupSlug": "ford-focus",
    "label": "Mk2 (Europe) (2004–2011)",
    "chassisCodes": [
      "C307"
    ],
    "productionStart": 2004,
    "productionEnd": 2011
  },
  {
    "slug": "ford-focus-mk3-europe-c346",
    "modelGroupSlug": "ford-focus",
    "label": "Mk3 (Europe) (2010–2018)",
    "chassisCodes": [
      "C346"
    ],
    "productionStart": 2010,
    "productionEnd": 2018
  },
  {
    "slug": "ford-fiesta-mk5-european-numbering-b256",
    "modelGroupSlug": "ford-fiesta",
    "label": "Mk5 (European numbering) (2001–2008)",
    "chassisCodes": [
      "B256"
    ],
    "productionStart": 2001,
    "productionEnd": 2008
  },
  {
    "slug": "ford-fiesta-mk6-european-numbering-b299",
    "modelGroupSlug": "ford-fiesta",
    "label": "Mk6 (European numbering) (2008–2017)",
    "chassisCodes": [
      "B299"
    ],
    "productionStart": 2008,
    "productionEnd": 2017
  },
  {
    "slug": "ford-fiesta-mk7-european-numbering-b479",
    "modelGroupSlug": "ford-fiesta",
    "label": "Mk7 (European numbering) (2017–2023)",
    "chassisCodes": [
      "B479"
    ],
    "productionStart": 2017,
    "productionEnd": 2023
  },
  {
    "slug": "ford-mondeo-mk3-europe-cd132",
    "modelGroupSlug": "ford-mondeo",
    "label": "Mk3 (Europe) (2000–2007)",
    "chassisCodes": [
      "CD132"
    ],
    "productionStart": 2000,
    "productionEnd": 2007
  },
  {
    "slug": "ford-mondeo-mk4-europe-eucd",
    "modelGroupSlug": "ford-mondeo",
    "label": "Mk4 (Europe) (2007–2014)",
    "chassisCodes": [],
    "productionStart": 2007,
    "productionEnd": 2014
  },
  {
    "slug": "ford-mondeo-mk5-europe-cd391",
    "modelGroupSlug": "ford-mondeo",
    "label": "Mk5 (Europe) (2014–2022)",
    "chassisCodes": [
      "CD391"
    ],
    "productionStart": 2014,
    "productionEnd": 2022
  },
  {
    "slug": "ford-kuga-kuga-i-c394",
    "modelGroupSlug": "ford-kuga",
    "label": "Kuga I (2008–2012)",
    "chassisCodes": [
      "C394"
    ],
    "productionStart": 2008,
    "productionEnd": 2012
  },
  {
    "slug": "ford-kuga-kuga-ii-c520",
    "modelGroupSlug": "ford-kuga",
    "label": "Kuga II (2012–2019)",
    "chassisCodes": [
      "C520"
    ],
    "productionStart": 2012,
    "productionEnd": 2019
  },
  {
    "slug": "renault-clio-clio-ii-x65",
    "modelGroupSlug": "renault-clio",
    "label": "Clio II (1998–2012)",
    "chassisCodes": [
      "X65"
    ],
    "productionStart": 1998,
    "productionEnd": 2012
  },
  {
    "slug": "renault-clio-clio-iii-x85",
    "modelGroupSlug": "renault-clio",
    "label": "Clio III (2005–2014)",
    "chassisCodes": [
      "X85"
    ],
    "productionStart": 2005,
    "productionEnd": 2014
  },
  {
    "slug": "renault-clio-clio-iv-x98",
    "modelGroupSlug": "renault-clio",
    "label": "Clio IV (2012–2020)",
    "chassisCodes": [
      "X98"
    ],
    "productionStart": 2012,
    "productionEnd": 2020
  },
  {
    "slug": "renault-megane-megane-ii-x84",
    "modelGroupSlug": "renault-megane",
    "label": "Megane II (2002–2009)",
    "chassisCodes": [
      "X84"
    ],
    "productionStart": 2002,
    "productionEnd": 2009
  },
  {
    "slug": "renault-megane-megane-iii-x95",
    "modelGroupSlug": "renault-megane",
    "label": "Megane III (2008–2016)",
    "chassisCodes": [
      "X95"
    ],
    "productionStart": 2008,
    "productionEnd": 2016
  },
  {
    "slug": "renault-megane-megane-iv-xfb",
    "modelGroupSlug": "renault-megane",
    "label": "Megane IV (2016–2024)",
    "chassisCodes": [],
    "productionStart": 2016,
    "productionEnd": 2024
  },
  {
    "slug": "renault-scenic-scenic-ii-jm",
    "modelGroupSlug": "renault-scenic",
    "label": "Scenic II (2003–2009)",
    "chassisCodes": [],
    "productionStart": 2003,
    "productionEnd": 2009
  },
  {
    "slug": "renault-scenic-scenic-iii-jz",
    "modelGroupSlug": "renault-scenic",
    "label": "Scenic III (2009–2016)",
    "chassisCodes": [],
    "productionStart": 2009,
    "productionEnd": 2016
  },
  {
    "slug": "renault-scenic-scenic-iv-jfa-rfa",
    "modelGroupSlug": "renault-scenic",
    "label": "Scenic IV (2016–2023)",
    "chassisCodes": [],
    "productionStart": 2016,
    "productionEnd": 2023
  },
  {
    "slug": "renault-laguna-laguna-ii-x74",
    "modelGroupSlug": "renault-laguna",
    "label": "Laguna II (2001–2007)",
    "chassisCodes": [
      "X74"
    ],
    "productionStart": 2001,
    "productionEnd": 2007
  },
  {
    "slug": "renault-laguna-laguna-iii-x91",
    "modelGroupSlug": "renault-laguna",
    "label": "Laguna III (2007–2015)",
    "chassisCodes": [
      "X91"
    ],
    "productionStart": 2007,
    "productionEnd": 2015
  },
  {
    "slug": "peugeot-206-206-206-t1",
    "modelGroupSlug": "peugeot-206",
    "label": "206 / 206+ (1998–2012)",
    "chassisCodes": [
      "T1"
    ],
    "productionStart": 1998,
    "productionEnd": 2012
  },
  {
    "slug": "peugeot-207-207-a7",
    "modelGroupSlug": "peugeot-207",
    "label": "207 (2006–2014)",
    "chassisCodes": [
      "A7"
    ],
    "productionStart": 2006,
    "productionEnd": 2014
  },
  {
    "slug": "peugeot-307-307-t5",
    "modelGroupSlug": "peugeot-307",
    "label": "307 (2001–2009)",
    "chassisCodes": [
      "T5"
    ],
    "productionStart": 2001,
    "productionEnd": 2009
  },
  {
    "slug": "peugeot-308-308-i-t7",
    "modelGroupSlug": "peugeot-308",
    "label": "308 I (2007–2015)",
    "chassisCodes": [
      "T7"
    ],
    "productionStart": 2007,
    "productionEnd": 2015
  },
  {
    "slug": "peugeot-308-308-ii-t9",
    "modelGroupSlug": "peugeot-308",
    "label": "308 II (2013–2021)",
    "chassisCodes": [
      "T9"
    ],
    "productionStart": 2013,
    "productionEnd": 2021
  },
  {
    "slug": "citroen-c3-c3-i-fc-fn",
    "modelGroupSlug": "citroen-c3",
    "label": "C3 I (2002–2009)",
    "chassisCodes": [],
    "productionStart": 2002,
    "productionEnd": 2009
  },
  {
    "slug": "citroen-c3-c3-ii-sc",
    "modelGroupSlug": "citroen-c3",
    "label": "C3 II (2009–2016)",
    "chassisCodes": [],
    "productionStart": 2009,
    "productionEnd": 2016
  },
  {
    "slug": "citroen-c4-c4-i-lc-la",
    "modelGroupSlug": "citroen-c4",
    "label": "C4 I (2004–2010)",
    "chassisCodes": [],
    "productionStart": 2004,
    "productionEnd": 2010
  },
  {
    "slug": "citroen-c4-c4-ii-b7",
    "modelGroupSlug": "citroen-c4",
    "label": "C4 II (2010–2018)",
    "chassisCodes": [
      "B7"
    ],
    "productionStart": 2010,
    "productionEnd": 2018
  },
  {
    "slug": "citroen-c5-c5-i-dc-de-facelift-rc-re",
    "modelGroupSlug": "citroen-c5",
    "label": "C5 I (2001–2008)",
    "chassisCodes": [],
    "productionStart": 2001,
    "productionEnd": 2008
  },
  {
    "slug": "citroen-c5-c5-ii-often-listed-as-c5-iii-rd-td",
    "modelGroupSlug": "citroen-c5",
    "label": "C5 II (often listed as C5 III) (2008–2017)",
    "chassisCodes": [],
    "productionStart": 2008,
    "productionEnd": 2017
  },
  {
    "slug": "skoda-octavia-octavia-i-1u",
    "modelGroupSlug": "skoda-octavia",
    "label": "Octavia I (1996–2010)",
    "chassisCodes": [
      "1U"
    ],
    "productionStart": 1996,
    "productionEnd": 2010
  },
  {
    "slug": "skoda-octavia-octavia-ii-1z",
    "modelGroupSlug": "skoda-octavia",
    "label": "Octavia II (2004–2013)",
    "chassisCodes": [
      "1Z"
    ],
    "productionStart": 2004,
    "productionEnd": 2013
  },
  {
    "slug": "skoda-octavia-octavia-iii-5e",
    "modelGroupSlug": "skoda-octavia",
    "label": "Octavia III (2012–2020)",
    "chassisCodes": [
      "5E"
    ],
    "productionStart": 2012,
    "productionEnd": 2020
  },
  {
    "slug": "skoda-fabia-fabia-i-6y",
    "modelGroupSlug": "skoda-fabia",
    "label": "Fabia I (1999–2008)",
    "chassisCodes": [
      "6Y"
    ],
    "productionStart": 1999,
    "productionEnd": 2008
  },
  {
    "slug": "skoda-fabia-fabia-ii-5j",
    "modelGroupSlug": "skoda-fabia",
    "label": "Fabia II (2007–2014)",
    "chassisCodes": [
      "5J"
    ],
    "productionStart": 2007,
    "productionEnd": 2014
  },
  {
    "slug": "skoda-fabia-fabia-iii-nj",
    "modelGroupSlug": "skoda-fabia",
    "label": "Fabia III (2014–2022)",
    "chassisCodes": [],
    "productionStart": 2014,
    "productionEnd": 2022
  },
  {
    "slug": "skoda-superb-superb-i-3u",
    "modelGroupSlug": "skoda-superb",
    "label": "Superb I (2001–2008)",
    "chassisCodes": [
      "3U"
    ],
    "productionStart": 2001,
    "productionEnd": 2008
  },
  {
    "slug": "skoda-superb-superb-ii-3t",
    "modelGroupSlug": "skoda-superb",
    "label": "Superb II (2008–2015)",
    "chassisCodes": [
      "3T"
    ],
    "productionStart": 2008,
    "productionEnd": 2015
  },
  {
    "slug": "skoda-superb-superb-iii-3v",
    "modelGroupSlug": "skoda-superb",
    "label": "Superb III (2015–2024)",
    "chassisCodes": [
      "3V"
    ],
    "productionStart": 2015,
    "productionEnd": 2024
  },
  {
    "slug": "toyota-corolla-corolla-ix-e120-e130",
    "modelGroupSlug": "toyota-corolla",
    "label": "Corolla IX (2000–2007)",
    "chassisCodes": [
      "E120",
      "E130"
    ],
    "productionStart": 2000,
    "productionEnd": 2007
  },
  {
    "slug": "toyota-corolla-corolla-x-european-sedan-scope-e140-e150",
    "modelGroupSlug": "toyota-corolla",
    "label": "Corolla X (European sedan scope) (2006–2013)",
    "chassisCodes": [
      "E140",
      "E150"
    ],
    "productionStart": 2006,
    "productionEnd": 2013
  },
  {
    "slug": "toyota-corolla-corolla-xi-european-sedan-scope-e170-e180",
    "modelGroupSlug": "toyota-corolla",
    "label": "Corolla XI (European sedan scope) (2013–2019)",
    "chassisCodes": [
      "E170",
      "E180"
    ],
    "productionStart": 2013,
    "productionEnd": 2019
  },
  {
    "slug": "toyota-avensis-avensis-i-t22",
    "modelGroupSlug": "toyota-avensis",
    "label": "Avensis I (1997–2003)",
    "chassisCodes": [
      "T22"
    ],
    "productionStart": 1997,
    "productionEnd": 2003
  },
  {
    "slug": "toyota-avensis-avensis-ii-t25",
    "modelGroupSlug": "toyota-avensis",
    "label": "Avensis II (2003–2009)",
    "chassisCodes": [
      "T25"
    ],
    "productionStart": 2003,
    "productionEnd": 2009
  },
  {
    "slug": "toyota-avensis-avensis-iii-t27",
    "modelGroupSlug": "toyota-avensis",
    "label": "Avensis III (2008–2018)",
    "chassisCodes": [
      "T27"
    ],
    "productionStart": 2008,
    "productionEnd": 2018
  },
  {
    "slug": "toyota-rav4-rav4-ii-xa20",
    "modelGroupSlug": "toyota-rav4",
    "label": "RAV4 II (2000–2005)",
    "chassisCodes": [
      "XA20"
    ],
    "productionStart": 2000,
    "productionEnd": 2005
  },
  {
    "slug": "toyota-rav4-rav4-iii-xa30",
    "modelGroupSlug": "toyota-rav4",
    "label": "RAV4 III (2005–2012)",
    "chassisCodes": [
      "XA30"
    ],
    "productionStart": 2005,
    "productionEnd": 2012
  },
  {
    "slug": "toyota-rav4-rav4-iv-xa40",
    "modelGroupSlug": "toyota-rav4",
    "label": "RAV4 IV (2012–2018)",
    "chassisCodes": [
      "XA40"
    ],
    "productionStart": 2012,
    "productionEnd": 2018
  },
  {
    "slug": "honda-civic-civic-vii-eu-ep-es-em",
    "modelGroupSlug": "honda-civic",
    "label": "Civic VII (2000–2005)",
    "chassisCodes": [],
    "productionStart": 2000,
    "productionEnd": 2005
  },
  {
    "slug": "honda-civic-civic-viii-european-hatch-fk-fn",
    "modelGroupSlug": "honda-civic",
    "label": "Civic VIII - European hatch (2005–2011)",
    "chassisCodes": [],
    "productionStart": 2005,
    "productionEnd": 2011
  },
  {
    "slug": "honda-civic-civic-viii-sedan-fd-fa",
    "modelGroupSlug": "honda-civic",
    "label": "Civic VIII - sedan (2005–2012)",
    "chassisCodes": [],
    "productionStart": 2005,
    "productionEnd": 2012
  },
  {
    "slug": "honda-civic-civic-ix-european-hatch-fk",
    "modelGroupSlug": "honda-civic",
    "label": "Civic IX - European hatch (2011–2017)",
    "chassisCodes": [],
    "productionStart": 2011,
    "productionEnd": 2017
  },
  {
    "slug": "honda-civic-civic-ix-sedan-fb",
    "modelGroupSlug": "honda-civic",
    "label": "Civic IX - sedan (2011–2016)",
    "chassisCodes": [],
    "productionStart": 2011,
    "productionEnd": 2016
  },
  {
    "slug": "honda-cr-v-cr-v-ii-rd4-rd9",
    "modelGroupSlug": "honda-cr-v",
    "label": "CR-V II (2001–2006)",
    "chassisCodes": [],
    "productionStart": 2001,
    "productionEnd": 2006
  },
  {
    "slug": "honda-cr-v-cr-v-iii-re3-re7",
    "modelGroupSlug": "honda-cr-v",
    "label": "CR-V III (2006–2012)",
    "chassisCodes": [],
    "productionStart": 2006,
    "productionEnd": 2012
  },
  {
    "slug": "honda-cr-v-cr-v-iv-rm1-rm4",
    "modelGroupSlug": "honda-cr-v",
    "label": "CR-V IV (2011–2018)",
    "chassisCodes": [],
    "productionStart": 2011,
    "productionEnd": 2018
  },
  {
    "slug": "fiat-punto-punto-ii-188",
    "modelGroupSlug": "fiat-punto",
    "label": "Punto II (1999–2012)",
    "chassisCodes": [
      "188"
    ],
    "productionStart": 1999,
    "productionEnd": 2012
  },
  {
    "slug": "fiat-punto-grande-punto-punto-evo-punto-199",
    "modelGroupSlug": "fiat-punto",
    "label": "Grande Punto / Punto Evo / Punto (2005–2018)",
    "chassisCodes": [
      "199"
    ],
    "productionStart": 2005,
    "productionEnd": 2018
  },
  {
    "slug": "fiat-panda-panda-ii-169",
    "modelGroupSlug": "fiat-panda",
    "label": "Panda II (2003–2012)",
    "chassisCodes": [
      "169"
    ],
    "productionStart": 2003,
    "productionEnd": 2012
  },
  {
    "slug": "fiat-doblo-doblo-i-223",
    "modelGroupSlug": "fiat-doblo",
    "label": "Doblo I (2000–2010)",
    "chassisCodes": [
      "223"
    ],
    "productionStart": 2000,
    "productionEnd": 2010
  },
  {
    "slug": "fiat-doblo-doblo-ii-263",
    "modelGroupSlug": "fiat-doblo",
    "label": "Doblo II (2009–2022)",
    "chassisCodes": [
      "263"
    ],
    "productionStart": 2009,
    "productionEnd": 2022
  },
  {
    "slug": "nissan-qashqai-qashqai-i-j10",
    "modelGroupSlug": "nissan-qashqai",
    "label": "Qashqai I (2006–2013)",
    "chassisCodes": [
      "J10"
    ],
    "productionStart": 2006,
    "productionEnd": 2013
  },
  {
    "slug": "nissan-qashqai-qashqai-ii-j11",
    "modelGroupSlug": "nissan-qashqai",
    "label": "Qashqai II (2013–2021)",
    "chassisCodes": [
      "J11"
    ],
    "productionStart": 2013,
    "productionEnd": 2021
  },
  {
    "slug": "nissan-x-trail-x-trail-i-t30",
    "modelGroupSlug": "nissan-x-trail",
    "label": "X-Trail I (2000–2007)",
    "chassisCodes": [
      "T30"
    ],
    "productionStart": 2000,
    "productionEnd": 2007
  },
  {
    "slug": "nissan-x-trail-x-trail-ii-t31",
    "modelGroupSlug": "nissan-x-trail",
    "label": "X-Trail II (2007–2013)",
    "chassisCodes": [
      "T31"
    ],
    "productionStart": 2007,
    "productionEnd": 2013
  },
  {
    "slug": "nissan-x-trail-x-trail-iii-t32",
    "modelGroupSlug": "nissan-x-trail",
    "label": "X-Trail III (2013–2022)",
    "chassisCodes": [
      "T32"
    ],
    "productionStart": 2013,
    "productionEnd": 2022
  },
  {
    "slug": "nissan-micra-micra-iii-k12",
    "modelGroupSlug": "nissan-micra",
    "label": "Micra III (2002–2010)",
    "chassisCodes": [
      "K12"
    ],
    "productionStart": 2002,
    "productionEnd": 2010
  },
  {
    "slug": "nissan-micra-micra-iv-k13",
    "modelGroupSlug": "nissan-micra",
    "label": "Micra IV (2010–2017)",
    "chassisCodes": [
      "K13"
    ],
    "productionStart": 2010,
    "productionEnd": 2017
  }
];
